name: Update Pac-Man
on:
    schedule:
        - cron: "0 */12 * * *" # Update setiap 12 jam
    workflow_dispatch:

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Generate Pac-Man
              uses: abozanona/pacman-contribution-graph@main
              with:
                  github_user_name: "DianKartiko" # Ganti dengan username Anda
            - name: Push Changes
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"
                  git add .
                  git commit -m "Update Pac-Man animation"
                  git push
